### ISSUE TITLE
Test issue 01, Bug

### ISSUE THREAD

**Issue by heckl** [ScutumSoft/Ledger-Commander#1]
There is a bug at xy. Please fix it.

**Comment by ScutumSoft** [comment]
It will be fixed in 2 weeks. 

I try to update this comment.

**Comment by heckl** [comment]
There is no fix yet.

**Comment by ScutumSoft** [comment]
Now there is a new version.

**Comment by heckl** [comment]
No it is not fixed.

**Comment by ScutumSoft** [comment]
It is, check again.

**Comment by heckl** [comment]
Now I see.
